//
//  Workspace.swift
//  __APP_NAME__
//

import ProjectDescription

let workspace = Workspace(
  name: "__APP_NAME__",
  projects: [
    ".",
    "Modules/Core/AppCore",
    "Modules/Core/CommonUI",
    "Modules/Core/CoreNavigation",
    "Modules/Features/HomeFeature",
    "Modules/Features/ProfileFeature"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .disabled
  )
)
