//
//  Workspace.swift
//  __APP_NAME__
//

import ProjectDescription

let workspace = Workspace(
  name: "__APP_NAME__",
  projects: [
    ".",
    "Modules/SharedModels",
    "Modules/CounterFeature",
    "Modules/SettingsFeature",
    "Modules/AppFeature"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .disabled
  )
)
